name: lint

on:
  push:
    branches:
      # Run on pushes to default branch
      - main
  # Run against pull requests
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: ⬇️ lint markdown files
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          config: ".markdownlint.json"
          args: "**/*.md .github/**/*.md"
